### ISSUE TITLE
can't open docker generic camera from flask server

### ISSUE THREAD

**Issue by riolaf05** [riolaf05/iot-home#51]
`During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/Codice/flask-https/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/pi/Codice/flask-https/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/pi/Codice/flask-https/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/pi/Codice/flask-https/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/pi/Codice/flask-https/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/pi/Codice/flask-https/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/pi/Codice/flask-https/lib/python3.7/site-packages/flask_httpauth.py", line 163, in decorated
    return f(*args, **kwargs)
  File "server.py", line 31, in docker
    client.containers.run("rio05docker/raspberry_container_camera:v1", "/home/scripts/camera/generic_browser_camera.py", name='camera', remove=True, privileged=True, detach=True, devices=devices, environment=environments, ports=ports)
  File "/home/pi/Codice/flask-https/lib/python3.7/site-packages/docker/models/containers.py", line 816, in run
    container.start()
  File "/home/pi/Codice/flask-https/lib/python3.7/site-packages/docker/models/containers.py", line 404, in start
    return self.client.api.start(self.id, **kwargs)
  File "/home/pi/Codice/flask-https/lib/python3.7/site-packages/docker/utils/decorators.py", line 19, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/home/pi/Codice/flask-https/lib/python3.7/site-packages/docker/api/container.py", line 1108, in start
    self._raise_for_status(res)
  File "/home/pi/Codice/flask-https/lib/python3.7/site-packages/docker/api/client.py", line 261, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/home/pi/Codice/flask-https/lib/python3.7/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.APIError: 400 Client Error: Bad Request ("OCI runtime create failed: container_linux.go:346: starting container process caused "exec: \"/home/scripts/camera/generic_browser_camera.py\": permission denied": unknown")`

**Comment by riolaf05** [comment]
https://github.com/riolaf05/iot-home/tree/home-surveillance/Raspberry-containers/generic_camera/server.py
